package simonsays;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.*;
import simonsays.simonbutton.SimonButton;

public class GamePanel extends JFrame implements ActionListener
    {
        //Initializing attributes and variables for manipulation
        SimonButton[] simonButtons;
        JButton btnStart;
        JLabel statusLabel;

        //Stores the random sequence generated by Random
        List<Integer> sequence;
        int inputIndex;
        //Flag if the user can or can not input
        boolean takingInput;
        //Timer for how long the flash will last
        Timer flashTimer;
        int flashIndex;
        //Utilized on method
        boolean isFlashing;

        private final Random random = new Random();
        
        public GamePanel ()
            {
                //Default JFrame Configurations
                this.setTitle("Simon Says");
                this.setSize(600, 600);
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.setLocationRelativeTo(null);
                this.setLayout(new BorderLayout());
                this.setResizable(false);

                //Initializing Array List of button sequences
                sequence = new ArrayList<>();
                takingInput = false;

                //Insantiating Simon Buttons Array
                simonButtons = new SimonButton[4]; //Contains Red, Blue, Green, and Yellow

                //Insantiating each button
                simonButtons[0] = new SimonButton(this, new Color(150, 0, 0), new Color(255, 0, 0), 0);
                simonButtons[1] = new SimonButton(this, new Color(0, 0, 150), new Color(0, 0, 255), 1);
                simonButtons[2] = new SimonButton(this, new Color(0, 150, 0), new Color(0, 255, 0), 2);
                simonButtons[3] = new SimonButton(this, new Color(150, 150, 0), new Color(255, 255, 0), 3);

                // Organizing buttons in a Grid
                JPanel gameGrid = new JPanel();
                gameGrid.setLayout(new GridLayout(2, 2));
                gameGrid.add(simonButtons[2]); // Green
                gameGrid.add(simonButtons[0]); // Red
                gameGrid.add(simonButtons[3]); // Yellow
                gameGrid.add(simonButtons[1]); // Blue
                
                //Adding the Game Grid to actual panel
                add(gameGrid, BorderLayout.CENTER);

                //Custom Font (If Failed will utilize Windows Default) [Utilize InputStream so that can still get assets when compiled to .exe]
                Font customFont;
                try
                    {
                        InputStream is = getClass().getResourceAsStream("/simonsays/assets/fonts/Montserrat-Bold.ttf");
                        customFont = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(18f);
                    }
                catch (Exception e)
                    {
                        customFont = new Font("Arial", Font.BOLD, 18);
                    }

                // Control Panel
                JPanel controlPanel = new JPanel();
                btnStart = new JButton("Start Game");
                btnStart.setFont(customFont);
                btnStart.setFocusPainted(false);
                btnStart.setBorderPainted(false);
                //Add an Action listener to the Button
                btnStart.addActionListener(this);
                
                //Setting text to Status Label
                statusLabel = new JLabel("Press Start to Play");
                statusLabel.setFont(customFont);
                
                //Adding Start Button and Status Label inside of Control Panel
                controlPanel.add(btnStart);
                controlPanel.add(statusLabel);

                //Adding the Control Panel to the Bottom of the JFrame
                add(controlPanel, BorderLayout.SOUTH);

                //Initializing a Timer
                flashTimer = new Timer(750, e -> handleFlash());

                //Ensures it will be visible
                setVisible(true);
            }

        //Method when players pressed Start Button
        private void startGame ()
            {
                //Clearing the whole list
                sequence.clear();
                inputIndex = 0;
                takingInput = false;
                //Ensures Start Button becomes disabled
                btnStart.setEnabled(false);
                statusLabel.setText("Watch the Sequence...");
                addToSequence();
            }

        //Method Randomizer for the Game
        private void addToSequence ()
            {
                //Adding random numnbers onto the sequence
                sequence.add(random.nextInt(4));
                playSequence();
                isFlashing = true;
            }

        //Play the Randomizer's Output and flash the buttons
        private void playSequence ()
            {
                takingInput = false;
                flashIndex = 0;
                isFlashing = true;
                flashTimer.start();
            }

        private void handleFlash ()
            {
                if (flashIndex >= sequence.size())
                    {
                        //Stop the timer
                        flashTimer.stop();
                        isFlashing = false;
                        takingInput = true;
                        inputIndex = 0;
                        statusLabel.setText("Your Turn!");
                        return;
                    }

                int colorCode = sequence.get(flashIndex);
                SimonButton btn = getButtonByCode(colorCode);

                if (btn != null)
                    {
                        btn.flash();
                    }
                flashIndex++;
            }

        //Method to Identify which button was pressed according to code
        private SimonButton getButtonByCode (int code)
            {
                //Returns the Button that's pressed [Red = 0; Blue = 1; Green = 2; Yellow = 3]
                if (code >= 0 && code < simonButtons.length)
                    {
                        return simonButtons[code];
                    }
                //Will return nothing IF it's not on the scale of 0-3
                return null;
            }

        public boolean isTakingInput() {
            return takingInput;
        }

        //Method for Input of User
        public void handleInput (int code)
            {
                //If it's not taking input just end
                if (!takingInput) return;

                if (sequence.get(inputIndex) == code)
                    {
                        //Corect
                        inputIndex++;

                        if (inputIndex >= sequence.size())
                            {
                                //Complete the round
                                takingInput = false;
                                statusLabel.setText("Correct! Time for the Next Round!");
                                Timer nextRoundTimer = new Timer(1000, e -> 
                                    {
                                        //Adding the sequence
                                        addToSequence();
                                        //Make timer stop
                                        ((Timer)e.getSource()).stop();
                                    });
                                //Stop repetition
                                nextRoundTimer.setRepeats(false);
                                nextRoundTimer.start();
                            }
                    }
                else
                    {
                        gameOver();
                    }
            }

        //Method for handling Game Over of user
        private void gameOver()
            {   
                takingInput = false;
                //sequence.size is all of the correct answers of the user and subtracting to 1 to be true to the score due to index of programming
                statusLabel.setText("<html>Game Over!<br>" + "Score: " + (sequence.size() - 1));
                btnStart.setEnabled(true);
                flashAll();
            }

        //Make buttons flash
        private void flashAll()
            {
                simonButtons[0].flash();
                simonButtons[1].flash();
                simonButtons[2].flash();
                simonButtons[3].flash();
            }

        //Handle Start Button Logic
        @Override
        public void actionPerformed (ActionEvent e)
            {
                if (e.getSource() == btnStart)
                    {
                        startGame();
                    }
            }
    }