package games.simonsays;

import games.simonsays.simonbutton.SimonButton;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.*;

public class GamePanel extends JFrame implements ActionListener
    {
        //Initializing attributes and variables for manipulation
        SimonButton[] simonButtons;
        JButton btnStart;
        JLabel statusLabel;

        //Stores the random sequence generated by Random
        List<Integer> sequence;
        int inputIndex;
        //Flag if the user can or can not input
        boolean takingInput;
        //Timer for how long the flash will last
        Timer flashTimer;
        int flashIndex;
        //Utilized on method
        boolean isFlashing;

        private final Random random = new Random();
        
        public GamePanel ()
            {
                //Default JFrame Configurations
                this.setTitle("Simon Says");
                this.setSize(600, 600);
                this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.setLocationRelativeTo(null);
                this.setLayout(new BorderLayout());
                this.setResizable(false);

                //Initializing Array List of button sequences
                sequence = new ArrayList<>();
                takingInput = false;

                //Insantiating Simon Buttons Array
                simonButtons = new SimonButton[4]; //Contains Red, Blue, Green, and Yellow

                //Insantiating each button
                simonButtons[0] = new SimonButton(this, new Color(150, 0, 0), new Color(255, 0, 0), 0);
                simonButtons[0].setPreferredSize(new Dimension(200, 200));
                simonButtons[0].setMinimumSize(new Dimension(200, 200));
                simonButtons[0].setMaximumSize(new Dimension(200, 200));

                simonButtons[1] = new SimonButton(this, new Color(0, 0, 150), new Color(0, 0, 255), 1);
                simonButtons[1].setPreferredSize(new Dimension(200, 200));
                simonButtons[1].setMinimumSize(new Dimension(200, 200));
                simonButtons[1].setMaximumSize(new Dimension(200, 200));

                simonButtons[2] = new SimonButton(this, new Color(0, 150, 0), new Color(0, 255, 0), 2);
                simonButtons[2].setPreferredSize(new Dimension(200, 200));
                simonButtons[2].setMinimumSize(new Dimension(200, 200));
                simonButtons[2].setMaximumSize(new Dimension(200, 200));

                simonButtons[3] = new SimonButton(this, new Color(150, 150, 0), new Color(255, 255, 0), 3);
                simonButtons[3].setPreferredSize(new Dimension(200, 200));
                simonButtons[3].setMinimumSize(new Dimension(200, 200));
                simonButtons[3].setMaximumSize(new Dimension(200, 200));

                // Organizing buttons in a Grid
                JPanel mainGameGrid = new JPanel(new GridBagLayout());
                //Default Configurations of Main Game Grid
                mainGameGrid.setBackground(Color.BLACK);
                mainGameGrid.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.GRAY));
                JPanel gameGrid = new JPanel(new GridLayout(2, 2));

                //Adding to the Grid Layout
                gameGrid.add(simonButtons[2]); // Green
                gameGrid.add(simonButtons[0]); // Red
                gameGrid.add(simonButtons[3]); // Yellow
                gameGrid.add(simonButtons[1]); // Blue
                
                //Adding to Main Game Grid for easier Centering
                mainGameGrid.add(gameGrid);

                //Adding the Game Grid to actual panel
                add(mainGameGrid, BorderLayout.CENTER);

                //Custom Font (If Failed will utilize Windows Default) [Utilize InputStream so that can still get assets when compiled to .exe]
                Font customFont;
                try
                    {
                        InputStream is = getClass().getResourceAsStream("/games/simonsays/assets/fonts/Montserrat-Bold.ttf");
                        customFont = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(24f);
                    }
                catch (Exception e)
                    {
                        customFont = new Font("Arial", Font.BOLD, 24);
                    }

                // Control Panel
                JPanel controlPanel = new JPanel();
                //Make it so that they get stacked vertically
                controlPanel.setLayout(new BoxLayout(controlPanel, BoxLayout.Y_AXIS));
                //Control Panel Default Configurations
                controlPanel.setBackground(Color.BLACK);
                btnStart = new JButton("Start Game");
                btnStart.setPreferredSize(new Dimension(150, 50));
                btnStart.setFont(customFont);
                btnStart.setFocusPainted(false);
                btnStart.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY));
                btnStart.setBackground(Color.decode("#06D6A0"));
                btnStart.setForeground(Color.BLACK);
                //Add an Action listener to the Button
                btnStart.addActionListener(this);
                
                //Setting text to Status Label
                statusLabel = new JLabel("Press Start to Play");
                statusLabel.setFont(customFont);
                //Make it visible from the Background Color
                statusLabel.setForeground(Color.WHITE);
                
                //Centering each component
                btnStart.setAlignmentX(Component.CENTER_ALIGNMENT);
                statusLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                statusLabel.setHorizontalAlignment(JLabel.CENTER);

                //Adding Start Button and Status Label inside of Control Panel, Adding Boxes before and after last components to center them
                controlPanel.add(Box.createRigidArea(new Dimension(0, 10)));
                controlPanel.add(statusLabel);
                controlPanel.add(Box.createRigidArea(new Dimension(0, 20)));
                controlPanel.add(btnStart);
                controlPanel.add(Box.createRigidArea(new Dimension(0, 20)));

                //Adding the Control Panel to the Bottom of the JFrame
                add(controlPanel, BorderLayout.SOUTH);

                //Initializing a Timer for how long Buttons Flash when game starts
                flashTimer = new Timer(750, e -> handleFlash());

                //Ensures it will be visible
                setVisible(true);
            }

        //Method when players pressed Start Button
        private void startGame ()
            {
                //Clearing the whole list
                sequence.clear();
                inputIndex = 0;
                takingInput = false;
                //Ensures Start Button becomes disabled
                btnStart.setEnabled(false);
                statusLabel.setText("Watch the Sequence...");
                addToSequence();
            }

        //Method Randomizer for the Game
        private void addToSequence ()
            {
                //Adding random numnbers onto the sequence
                sequence.add(random.nextInt(4));
                playSequence();
                isFlashing = true;
            }

        //Play the Randomizer's Output and flash the buttons
        private void playSequence ()
            {
                takingInput = false;
                flashIndex = 0;
                isFlashing = true;
                flashTimer.start();
            }

        //Method to ensure that Flashing stops once the end of the Flash Sequence is reached
        private void handleFlash ()
            {
                if (flashIndex >= sequence.size())
                    {
                        //Stop the timer
                        flashTimer.stop();
                        isFlashing = false;
                        takingInput = true;
                        inputIndex = 0;
                        statusLabel.setText("Your Turn!");
                        return;
                    }

                //Take the colorCode (Integer Value of the randomizer)
                int colorCode = sequence.get(flashIndex);
                //Create variable btn to check if the btn exists via the Button Code
                SimonButton btn = getButtonByCode(colorCode);

                //If it exists make it flash for 400ms
                if (btn != null)
                    {
                        btn.flash();
                    }
                
                //Increment to proceed to next random integer
                flashIndex++;
            }

        //Method to Identify which button was pressed according to code
        private SimonButton getButtonByCode (int code)
            {
                //Returns the Button that's pressed [Red = 0; Blue = 1; Green = 2; Yellow = 3]
                if (code >= 0 && code < simonButtons.length)
                    {
                        return simonButtons[code];
                    }
                //Will return nothing IF it's not on the scale of 0-3
                return null;
            }

        //Getter for takingInput
        public boolean isTakingInput() {
            return takingInput;
        }

        //Method for Input of User
        public void handleInput (int code)
            {
                //If it's not taking input just end
                if (!takingInput) return;

                if (sequence.get(inputIndex) == code)
                    {
                        //Corect
                        inputIndex++;

                        if (inputIndex >= sequence.size())
                            {
                                //Complete the round
                                takingInput = false;
                                statusLabel.setText("Correct! Time for the Next Round!");
                                Timer nextRoundTimer = new Timer(1000, e -> 
                                    {
                                        //Adding the sequence
                                        addToSequence();
                                        //Make timer stop
                                        ((Timer)e.getSource()).stop();
                                    });
                                //Stop repetition
                                nextRoundTimer.setRepeats(false);
                                nextRoundTimer.start();
                            }
                    }
                //If the user failed to follow the sequence call Game Over Method
                else
                    {
                        gameOver();
                    }
            }

        //Method for handling Game Over of user
        private void gameOver()
            {   
                takingInput = false;
                int userScore = sequence.size() - 1;
                //sequence.size is all of the correct answers of the user and subtracting to 1 to be true to the score due to index of programming
                statusLabel.setText("<html><center>Game Over!<br>" + "Score: " + userScore + "</center></html>");
                btnStart.setEnabled(true);
                flashAll();
            }

        //Make buttons flash
        private void flashAll()
            {
                simonButtons[0].flash();
                simonButtons[1].flash();
                simonButtons[2].flash();
                simonButtons[3].flash();
            }

        //Handle Start Button Logic
        @Override
        public void actionPerformed (ActionEvent e)
            {
                if (e.getSource() == btnStart)
                    {
                        //Start the Game
                        startGame();
                    }
            }
    }